config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'pages#home'

  get '/dashboard', to: 'projects#dashboard', as: :dashboard
  get '/next_question', to: 'questions#next_question'

  resources :buddies, only: %i[new create show update]
  resources :projects, only: %i[index new create show update]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :user_answers
  has_many :users, through: :user_answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buddy.rb
class Buddy < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :project
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :buddies
  has_many :projects
  has_many :user_answers
  has_many :answers, through: :user_answers
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController
  def index
    @buddys = Buddy.all
  end

  def new
    @buddy = Buddy.new
  end

  def show
    @buddy = Buddy.find(params[:id])
  end

  def create
    @buddy = Buddy.new(buddy_params)
    if @buddy.save
      redirect_to buddys_path
    else
      render 'new'
    end
  end

  def update
    @buddy = current_user.buddys.find(params[:id])

    if @buddy.update(buddy_params)
      redirect_to buddys_path, notice: 'Buddy was updated.'
    else
      render :edit
    end
  end

  def destroy
    @buddy = Buddy.find(params[:id])
    @buddy.destroy
    redirect_to buddys_path
  end

  private

  def buddy_params
    params.require(:buddy).permit(:name, :personality)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, status: :see_other
  end

  def dashboard
    # @recommended_projects = Project.where(category: current_user.interest)
    # @project = Project.find(current_user.project_id)
    # I think we can use this line below to access the buddy's name, love, etc.
    # @buddy = current_user.buddy
    # Not so sure how we will do this right now.
    # @progress =
  end
  private

  def project_params
    params.require(:project).permit(:name, :deadline, :category)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddies_helper.rb
module BuddiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ontrack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%# <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%# <%= render "shared/footer" %> 
  </body>
</html>

app/views/pages/home.html.erb
<div class="row homepage col-12">
  <%# paw %>
  <div class="paw">
    <ul>
      <li><i class="fa-solid fa-paw yellow-paw"></i></li>
      <li><i class="fa-solid fa-paw green-paw"></i></li>
      <li><i class="fa-solid fa-paw blue-paw"></i></li>
    </ul>
  </div>
  <%# banner %>
  <div class="bg-img d-flex">
    <div class="banner align-self-center">
      <h1>OnTrack</h1>
      <p>Discover your learning path</p>
      <button class="yellow-btn">
        <%= link_to "GET STARTED"%>
      </button>
      </div>
    </div>

    <%# paw %>
  <div class="paw">
    <ul>
      <li><i class="fa-solid fa-paw yellow-paw"></i></li>
      <li><i class="fa-solid fa-paw green-paw"></i></li>
      <li><i class="fa-solid fa-paw blue-paw"></i></li>
    </ul>
  </div>
</div>









<%#
 <button class="green-btn">
    <%= link_to "SIGN UP"%>
  <%# </button> %>

app/views/projects/dashboard.html.erb
<div class="container py-5 bg-body-tertiary">
  <h3 class="text-center">My Dashboard</h3>
  <div class="dashboard-container">
    <div class="my-info">
      <p>Latest Project:</p>
      <p>Upcoming Deadlines:</p>
      <p>Current Points:</p>
    </div>
    <div class="buddy-container">
      <%= cl_image_tag("https://res.cloudinary.com/du53mgiot/image/upload/v1691219849/dog_main.png", height: 150, crop: :fill) %>
      <p class="buddy-text">Hello!</p>
    </div>
    <div class="buddy-links text-center">
      <%= link_to dashboard_path do %>
        <i class="fa-solid fa-bone"></i>
      <% end %>
      <%= link_to dashboard_path do %>
        <i class="fa-solid fa-comments"></i>
      <% end %>
    </div>
    <div class="project-recommendations">
      <p>Place project recommendations here.</p>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<h1>Test!</h1>
<p>Projects: <%= @projects %></p>

app/views/projects/new.html.erb
<h1>Test!</h1>
<p>Create a new project on this page</p>

app/views/projects/show.html.erb
<h1>Test!</h1>
<p>Just one project: <%= @project %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>copyright &copy; OnTrack <span id="date">2023</span> all rights reserved</p>
  </div>
</footer> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>